'use client'
import './globals.css'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import Providers from "@/providers/providers";


const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//     title: 'Next App',
//     description: 'Generated by create next app',
// }
interface RootLayoutProps {
    children: ReactNode;
}
export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <Providers>
                {children}
            </Providers>
        </body>
        </html>
    )
}
