export {AddToHomeScreen} from './home-screen'
export {InstallPWA} from './install-pwa'
export {AddNewExapmle} from './add-new-example'
export {VideoRecorder} from './video-recorder'
export {QrReaderC} from './qr-reqder'
export {PhotoCam, PhotoWebCam} from './phote-cam'